% Set default parameters
default_para = struct(...

    'maxiter',      1e+3,...

    'opttol',       1e-6,...

    'c1ls',         1e-4,...

    'c2ls',         0.9,...

    'c1tr',         0.1,...

    'c2tr',         0.75,...

    'cgopttol',     1e-6,...

    'cgmaxiter',    1e+3,...

    'radius',       1.0,...

    'sr1updatetol', 1e-6);